services:
  # -------------------------
  # DATABASE
  # -------------------------
  postgres:
    image: postgres:16
    container_name: online_ticket_postgres
    restart: always
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # -------------------------
  # REDIS
  # -------------------------
  redis:
    image: redis:7-alpine
    container_name: online_ticket_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  redis-insight:
    image: redis/redis-stack:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redisinsightdata:/data
    depends_on:
      - redis

  # -------------------------
  # RABBITMQ
  # -------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: online_ticket_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  # -------------------------
  # IDENTITY SERVICE
  # -------------------------
  identity:
    build:
      context: ../../
      dockerfile: apps/identity-service/Dockerfile
    container_name: identity_service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../../apps/identity-service/.env
    environment:
      - DATABASE_URL=postgresql://identity_user:identity_pass@postgres:5432/identity_db?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  # -------------------------
  # PROFILE SERVICE
  # -------------------------
  profile:
    build:
      context: ../../
      dockerfile: apps/profile-service/Dockerfile
    container_name: profile_service
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ../../apps/profile-service/.env
    environment:
      - DATABASE_URL=postgresql://identity_user:identity_pass@postgres:5432/profile_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  # -------------------------
  # API GATEWAY
  # -------------------------
  api-gateway:
      build:
        context: ../../
        dockerfile: apps/api-gateway/Dockerfile
      container_name: api_gateway
      restart: always
      ports:
        - "8080:8080"
      environment:
        - HOST=0.0.0.0  # <--- ESSENCIAL
        - PORT=8080
        - IDENTITY_SERVICE_URL=http://identity_service:3000 # Use o container_name
        - PROFILE_SERVICE_URL=http://profile_service:3001
      depends_on:
        - identity
        - profile


  # -------------------------
  # PGWEB (DB UI)
  # -------------------------
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    ports:
      - '8081:8081'
    environment:
      - PGWEB_DATABASE_URL=postgres://identity_user:identity_pass@postgres:5432/identity_db?sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata:
  redisdata:
  redisinsightdata: